/*
 * Copyright (c) 2024, CATIE
 * SPDX-License-Identifier: Apache-2.0
 */

#ifndef ZEPHYR_DRIVERS_SENSOR_2SMPB_02E_2SMPB_02E_H_
#define ZEPHYR_DRIVERS_SENSOR_2SMPB_02E_2SMPB_02E_H_

#endif /* ZEPHYR_DRIVERS_SENSOR_2SMPB_02E_2SMPB_02E_H_ */
